copy ..\tamgu\include\*.h include
copy ..\tamgu\src\*.cxx src
copy ..\tamgu\allmaps\include\*.h allmaps\include
copy ..\tamgu\allmaps\src\*.cxx allmaps\src\
copy ..\tamgu\libsqlite\include\*.h libsqlite\include
copy ..\tamgu\libsqlite\src\*.cxx libsqlite\src\
copy ..\tamgu\libxml\include\*.h libxml\include
copy ..\tamgu\libxml\src\*.cxx libxml\src\
copy ..\tamgu\libwapiti\include\*.h libwapiti\include
copy ..\tamgu\libwapiti\src\*.cxx libwapiti\src\
copy ..\tamgu\liblinear\include\*.h liblinear\include
copy ..\tamgu\liblinear\src\*.cxx liblinear\src\
copy ..\tamgu\libpython\include\*.h libpython\include
copy ..\tamgu\libpython\src\*.cxx libpython\src\
copy ..\tamgu\libword2vec\include\*.h libword2vec\include
copy ..\tamgu\libword2vec\src\*.cxx libword2vec\src\
copy ..\tamgu\libcurl\include\*.h libcurl\include
copy ..\tamgu\libcurl\src\*.cxx libcurl\src\
copy ..\tamgu\libsound\include\*.h libsound\include
copy ..\tamgu\libsound\src\*.cxx libsound\src\
copy ..\tamgu\libgui\include\*.h libgui\include
copy ..\tamgu\libgui\src\*.cxx libgui\src\
