/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_naver_jtamgu_JTamgu */

#ifndef _Included_com_naver_jtamgu_JTamgu
#define _Included_com_naver_jtamgu_JTamgu
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_naver_jtamgu_JTamgu
 * Method:    LoadProgramImplementation
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_naver_jtamgu_JTamgu_LoadProgramImplementation
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_naver_jtamgu_JTamgu
 * Method:    LoadStringProgramImplementation
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_naver_jtamgu_JTamgu_LoadStringProgramImplementation
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_naver_jtamgu_JTamgu
 * Method:    ExecuteFunctionImplementation
 * Signature: (ILjava/lang/String;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_naver_jtamgu_JTamgu_ExecuteFunctionImplementation
  (JNIEnv *, jobject, jint, jstring, jobjectArray);

/*
 * Class:     com_naver_jtamgu_JTamgu
 * Method:    ExecuteFunctionArrayImplementation
 * Signature: (ILjava/lang/String;[Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_naver_jtamgu_JTamgu_ExecuteFunctionArrayImplementation
  (JNIEnv *, jobject, jint, jstring, jobjectArray);

/*
 * Class:     com_naver_jtamgu_JTamgu
 * Method:    CleanImplementation
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_naver_jtamgu_JTamgu_CleanImplementation
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_naver_jtamgu_JTamgu
 * Method:    CleanAllImplementation
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_naver_jtamgu_JTamgu_CleanAllImplementation
  (JNIEnv *, jobject);

/*
 * Class:     com_naver_jtamgu_JTamgu
 * Method:    TamguVersionImplementation
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_naver_jtamgu_JTamgu_TamguVersionImplementation
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
